name: 'Kubernetes Kustomize Resources Diff'
description: 'Get the diff of the resources applied on the cluster using kustomize'
branding:
  icon: terminal
  color: gray-dark
inputs:
  kustomize_folder:
    description: 'Folder from where kustomization.yaml resides'
    required: true
    default: '.'
  local_cluster:
    description: 'Wether the action will have local access to the kubernetes cluster'
    required: false
    default: false
    type: bool
  sources_folder:
    description: 'Folder from where helm sources resides'
    required: false
    default: 'sources'
  kubeconfig:
    description: 'Config to connect to kubernetes cluster (b64 encoded)'
    required: false
    default: ''
  sa-token:
    description: 'Service account token (b64 decoded)'
    required: false
    default: ''
  server-url:
    description: 'Server endpoint URL'
    required: false
    default: ''
  server-ca:
    description: 'Server CA (b64 encoded)'
    required: false
    default: ''
outputs:
  releases_diff:
    description: 'Helm Release diff'
  resources_diff:
    description: 'Helm Resources diff'
runs:
  using: 'docker'
  image: 'docker://aanogueira/helm-resources-diff:0.1.0'
  args:
    - ${{ inputs.kustomize_folder }}
    - ${{ inputs.server-url }}
    - ${{ inputs.server-ca }}
    - ${{ inputs.sa-token }}
    - ${{ inputs.kubeconfig }}
    - ${{ inputs.sources_folder }}
    - ${{ inputs.local_cluster }}
