name: 'Kubernetes Kustomize Resources Diff'
description: 'Get the diff of the resources applied on the cluster using kustomize'
inputs:
  folder:
    description: 'Folder from where to run the diff'
    required: true
    default: '.'
  kubeconfig:
    description: 'Config to connect to kubernetes cluster (b64 encoded)'
    required: false
    default: ''
  sa-token:
    description: 'Service account token (b64 decoded)'
    required: false
    default: ''
  server-url:
    description: 'Server endpoint URL'
    required: false
    default: ''
  server-ca:
    description: 'Server CA (b64 encoded)'
    required: false
    default: ''
outputs:
  diff: # id of output
    description: 'Resources diff'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.folder }}
    - ${{ inputs.server-url }}
    - ${{ inputs.server-ca }}
    - ${{ inputs.sa-token }}
    - ${{ inputs.kubeconfig }}
